name: 'manywin'
description: 'Build distributable windows python wheels'
inputs:
  name:
    description: "The artifact name for in-action storage"
    required: true
runs:
  using: "composite"
  steps:
  - name: Update python tools
    run: python -m pip install --upgrade pip setuptools wheel delvewheel
    shell: bash

  - uses: actions/checkout@v2

  - name: Build and fix the wheel
    shell: bash
    run: |
      python -m pip wheel --no-deps . -w wheelhouse
      delvewheel repair -w dist -v wheelhouse/*.whl

  - uses: actions/upload-artifact@v2
    with:
      name: ${{ inputs.name }}
      path: dist/*.whl
